name: CivSentinel-Backend

services:
  kafka:
    build:
      context: ./kafka
      dockerfile: Dockerfile

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    env_file:
      - scraper/.env
